### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by arihantdaga** [arihantdaga/mongoose-erd-generator-v2#1]
- [ ] Fix readme, attribute earlier package
- [ ] Fix package name and cli name
- [ ] Fix ERD generator - replace . with _ in relation names and entities name
- [ ] Fix github npmpublish workflow
